/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ClearButton: typeof import('./src/components/ui/ClearButton.vue')['default']
    FilterBar: typeof import('./src/components/FilterBar.vue')['default']
    FilterButton: typeof import('./src/components/ui/FilterButton.vue')['default']
    LoadingSpinner: typeof import('./src/components/ui/LoadingSpinner.vue')['default']
    Pagination: typeof import('./src/components/ui/Pagination.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    SearchItem: typeof import('./src/components/SearchItem.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Slider: typeof import('primevue/slider')['default']
  }
}
